### ISSUE TITLE
[TEST] Rasberry Pi OS Lite (arm32)

### ISSUE THREAD

**Issue by DanielSchetritt** [hyecheol123/Cloudflare-Public-Dynamic-IP-Update#12]
# OS Name and Version
Raspberry Pi OS Lite (arm32)

    Release date: May 7th 2021
    Kernel version: 5.10
```bash
$ uname -srm
Linux 5.10.52-v7+ armv7l
```
```bash
$ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
```

# Test Result
## 1. Current IP is same as record's IP, must see the proper message indicating the identity

Yes. It shows my cloudflare domain and my current public IP address. Clouflare already has the right IP address.

```bash
# IP Address and Domain redacted
$ bash ./Cloudflare-Public-Dynamic-IP-Update/cloudflare_dynamic_ip_update.bash 
current public IP address is xxx.xxx.xxx.190
sub.domain.tld: no needs to update
```

## 2. Current IP is not same as record's IP, record's IP must be updated and see the proper message indicating the record has been updated  

Yes. Here's how I did it:

First I changed my WAN IP address.
1. Check my current IP with `curl ip.me`
1. Turn off my internet modem
1. Log into my DD-WRT router's web interface.
1. Release my IP address on my WAN.
1. Spoof my router's MAC address
1. Turn on the modem
1. Wait for a new WAN IP address.
1. Double-check my IP address Changed with `curl ip.me`
`xxx.xxx.xxx.230`

Then I ran the script again.
```bash
# IP Address and Domain redacted
$ bash ./Cloudflare-Public-Dynamic-IP-Update/cloudflare_dynamic_ip_update.bash
current public IP address is xxx.xxx.xxx.230
sub.domain.tld: successfully updated to xxx.xxx.xxx.230
```

## 3. Has no connection, and see the error message

Yes.

I unplugged my modem and then ran the script.
```bash
$ bash ./Cloudflare-Public-Dynamic-IP-Update/cloudflare_dynamic_ip_update.bash
Check your internet connection, or google DNS server maybe interruptted
```

**Comment by hyecheol123** [comment]
Thanks for your effort. I will update README.md!!
