### ISSUE TITLE
[TEST]

### ISSUE THREAD

**Issue by amirulfple** [hyecheol123/Cloudflare-Public-Dynamic-IP-Update#2]
**OS Name and Version**
Indicate your OS Version  e.g. Raspberry Pi 3 B+ Running Raspbian

**Test Result**
**1.** *Current IP is same as record's IP, must see the proper message indicating the identity*
Your Answer (No) + Some Explanation
**2.** *Current IP is not same as record's IP, record's IP must be updated and see the proper message indicating the record has been updated*
Your Answer  (No) + Some Explanation
**3.** *Has no connection, and see the error message*
Your Answer (No) + Some Explanation

**Additional context**
Followed your guide, seems fine, changed all that need, but when i ran the script got error
Current Error when Running The Script :
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)

**Comment by hyecheol123** [comment]
Could you check whether you are using proper API Auth key?
The purpose of using `jq` library is to iterate through the result that has been retrieved from Cloudflare's API to check whether current server IP and Cloudflare's recorded IP are identical or not.

To test whether your API key is correct or not, try to use `curl` command to use API manually and check whether there exists any returned value or not.

**Comment by hyecheol123** [comment]
Here is the [manual for the Cloudflare API](https://api.cloudflare.com/)

**Comment by amirulfple** [comment]
Thank you, i modified the code a bit and it's working thumbs up

**Comment by hyecheol123** [comment]
@amirulfple Am I able to know which part you modified?

**Comment by amirulfple** [comment]
modified the api, instead of using api tokens, i used api global key.

**Comment by doughnet** [comment]
@amirulfple care to provide a pull with your modifications?

**Comment by hyecheol123** [comment]
If you are planning to make a PR of your modification, please also provide me some information what improvements you made.
I appreciate all of you for helping me out improving the code.
