### ISSUE TITLE
[TEST]

### ISSUE THREAD

**Issue by Nebour** [hyecheol123/Cloudflare-Public-Dynamic-IP-Update#3]
**OS Name and Version**
Raspbian GNU/Linux 10 (buster)

**Test Result**
**1.** *Current IP is same as record's IP, must see the proper message indicating the identity*
Yes
**2.** *Current IP is not same as record's IP, record's IP must be updated and see the proper message indicating the record has been updated*
Yes
**3.** *Has no connection, and see the error message*
Yes

**Additional context**
Required package for jq `sudo apt install jq`
Required package for dig `sudo apt install dnsutils`

**Comment by hyecheol123** [comment]
Thanks for the testing result.
To parse json properly, this shell script depends on jq and dig.

Are you confirming that my script also works on Raspbian GNU/Linux 10? Once you confirmed, I will add it to the tested OS list, and indicate your name(GitHub account) on the README.md page.

**Comment by Nebour** [comment]
Yes, the script is working fine on Raspbian 10. I'm currently running it from a Raspberry Pi 3B+.

**Comment by hyecheol123** [comment]
I just updated README.md
Thanks for your contribution
