### ISSUE TITLE
[BUG] API Token

### ISSUE THREAD

**Issue by doughnet** [hyecheol123/Cloudflare-Public-Dynamic-IP-Update#4]
**Describe the bug**
Having issues using bash script with jq.  It grabs the IP address properly.  API token is tested and working properly.

**To Reproduce**
1. Installed jq by doing apt install jq
2. Edit configuration file
3. Made bash script executable & ran it

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LXC VPS

**Additional context**

Dev:~/pkgs/Cloudflare-Public-Dynamic-IP-Update$ **./cloudflare_dynamic_ip_update.bash**
 ```
current public IP address is HIDDENIP#
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
```

**Comment by hyecheol123** [comment]
To make sure, while edit configuration file, you need to substitute everything after the equal sign including the square bracket rather than put the email and token inside of the square bracket.

Can you go and double check whether you edit configuration properly?

**Comment by doughnet** [comment]
Thanks.  I believe maybe the issue is that it wasn't specific which type of API Token is needed (global or  generated api tokens). After using the global api token and the zone-id it worked out fine.  I unfortunately figured out the complications with the global versus generated tokens when trying out another script that worked out for me on first try when it was specific on which to use.

Great script though!

**Comment by hyecheol123** [comment]
I will check whether the json response contains some error code that can Identify the message.

After I got some reply, I felt it will be better to make error checking procedure prior to parse all the required values from json reply from jq.

I will update the code, and thanks do far for indicating the errors!!

**Comment by hyecheol123** [comment]
To add some more information, this code utilizing either global API token or generated API token, and Zone-id.

It need zone-id to locate which zone(domain)'s DNS record to modify and either one of global or generated API token for authentication.

It should work fine with either two API tokens, however, I will take a look and write more comments about that later.
