### ISSUE TITLE
[BUG] The script works perfectly for subdomains but does not work for main domains.

### ISSUE THREAD

**Issue by erus00** [hyecheol123/Cloudflare-Public-Dynamic-IP-Update#6]
Hi,

Thanks a lot for this beautiful script.
I am using Centos8 server on a Google instance.
jq --version: jq-1.5
I also tried jq-1.6: Same result

I triple-checked my cloudfare_config and all seems fine.
I am using the correct zone ID as well.

The script works perfectly for subdomains but does not work for main domains.

For main domain I am getting the following error:

jq: error (at <stdin>:1): boolean (true) and boolean (false) cannot be added
record IP needs to be updated for mysite.commysite.commysite.commysite.commysite.com
Fail to update record IP of mysite.commysite.commysite.commysite.commysite.com\nPlease Check result!!
record IP needs to be updated for 
Fail to update record IP of \nPlease Check result!!
record IP needs to be updated for 
Fail to update record IP of \nPlease Check result!!
record IP needs to be updated for 
Fail to update record IP of \nPlease Check result!!
record IP needs to be updated for 
Fail to update record IP of \nPlease Check result!!

Am I doing something wrong?
Thanks a lot

**Comment by hyecheol123** [comment]
Can you confirm whether you are using global API authentication detail? I recently get an comments from others that my code only works with global token. I am working on fixing it, and it will be updated soon.

Moreover, can you also verify whether you put "mysite.com" only once in the cloudflare_config file? The hint to investigate this error is the fact that it prints out your domain more than once on the error message.

**Comment by hyecheol123** [comment]
Moreover, #5 indicates that my codes need to be fix in order to support the domain(names or address) that have more than one record(A, AAAA, MX, etc). This also need to be fixed, and will be done in few days.

**Comment by hyecheol123** [comment]
Now, the code has been fixed. It includes slightly better error messages.

Could you likely to pull the code and test on the new one??

**Comment by erus00** [comment]
Hi Jerry,

Sorry for the late answer.
I use the global API authentication.
I do have a series of A records configured in CF as I use subdomains (MX, CNAME, TXT as well).

I tried your updated script and applied "Record-Type=A" in the new cloudflare_config file.
=> It works perfectly on Centos 8!

I will modify your script to take the config values from variables rather than the file as I need to integrate it in another scripts for auto-updates after server migration.

Thanks a lot Jerry!

**Comment by hyecheol123** [comment]
Thanks for using my script.
I appreciate your feedback and please let me know if you have further questions!!

**Comment by erus00** [comment]
Thanks a lot Jerry,

Not a question but if you are looking for ideas to make the script more fun and more complete solution (as a stand-alone or as inserted within larger scipt) you could implement:

1- A choice at the beginning where people can choose to use the external file or incorporate the CF credentials directly in variables in the code (so they can instantly incorporate your script within a larger script like I am doing)

2- Automatically fetching the domains and associated zones so you could have a list of your domains directly presented to the user so they choose which domain they want to change. Here is an example below that I am sure you can make much better as I am not very good at coding! :-)

Thanks Jerry
===================

remote_site_selected='mysite.com'

```
######### THIS SCRIPTS FETCHES THE ZONE OF A DOMAIN NAME FROM CLOUDFLARE #########
# WE NEED remote_site_selected = site name
# We download the list and populate cloudflare_zones.list file
# Then we extract the ZONE from the list where site name is the one we look for.

read -r -p "RELOAD CLOUDFLARE ZONES LIST? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
then
  # COLLECT FROM CLOUDFLARE, STORE IN FILE
  curl -s -X GET "https://api.cloudflare.com/client/v4/zones/?per_page=100" -H "X-Auth-Email: $var_dns_cloudflare_email" -H "X-Auth-Key: $var_dns_cloudflare_api_key" -H "Content-Type: application/json"| jq -r '.result[] | "\(.id) \(.name)"' > cloudflare_zones.list
fi

# READ THE FILE AND LOAD IN cloudflare_zones
IFS=$'\n' read -d '' -r -a cloudflare_zones < cloudflare_zones.list

for zone in "${cloudflare_zones[@]}" # Each line of cloudf is read separatly
do
  for i in "${zone[@]}" # i is the line considered
    do
      IFS=' ' read -r -a result <<< "$i" # This converts a string with spaces in another array
      if [[ ${result[1]} == $remote_site_selected ]] # We test the second entry of array to select if = site we search for
	    then
        cloudflare_zone=${result[0]} # We call the first value of the array = ZONE ID
      fi
    done
done
######### ///THIS SCRIPTS FETCHES THE ZONE OF A DOMAIN NAME FROM CLOUDFLARE/// #########

echo ""
echo "WEBSITE SELECTED: "$remote_site_selected
echo "CLOUDFLARE ZONE: "$cloudflare_zone
```

**Comment by hyecheol123** [comment]
@erus00 Thanks for the comments.

1- This will be good feature update for future. I will definitely consider this as future improvement of this code.
2- For the list fetching and selection part, I think this would be maintained separate to the main update bash file, as we do not want to select the list all the time. As I am planning to make separated configuration helper bash script, I will accept your advice and add the feature to my next improvement.

Thanks for helping me make improvement of this code!!
